name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #- name: Ensure Clean Jupyter Notebooks
      #  uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --only-dev

      - name: Run ruff check
        run: uv run ruff check --fix ./src

      - name: Run ruff format
        run: uv run ruff format ./src

      #- name: Run pyright
      #  run: uv run pyright
