name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run tests
        run: uv run pytest -s

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: error
          path: tests/output/**/*.png
